### ISSUE TITLE
Event's description seems inaccurate

### ISSUE THREAD

**Issue by rjvitorino** [smart-data-models/dataModel.TourismDestinations#5]
While the global description states that an event is an upcoming or past event associated with this place, organization, or action.

The paragraph before the [Data Model description of properties](https://github.com/smart-data-models/dataModel.TourismDestinations/blob/master/Event/doc/spec.md#data-model-description-of-properties) says the following:

`This data model is based on the standard UNE178503. It is also compatible with schema.org. Some of the elements of schema.org has been adapted in this file https://smart-data-models.github.io/data-models/schema-org.json. This Type can be used on its own to describe a general TouristDestination, or be used as an additionalType to add tourist relevant properties to any other Place. A TouristDestination is defined as a Place that contains, or is colocated with, one or more TouristAttractions, often linked by a similar theme or interest to a particular touristType. The UNWTO defines Destination (main destination of a tourism trip) as the place visited that is central to the decision to take the trip.`

This seems a bit inaccurate from my perspective and should be adapted.

**Comment by albertoabellagarcia** [comment]
Thank you.
Could you be more precise?

**Comment by albertoabellagarcia** [comment]
Thank you for the comment.  I agree that could be improved. But we would like to see your alternative to make something more close to the users.
thanks again

**Comment by albertoabellagarcia** [comment]
You can reopen the issue and we will be glad to review your suggestions and to improve description.
